### ISSUE TITLE
RoadLanes unexpectedly twist when a RoadSegment is rotated

### ISSUE THREAD

**Issue by bdog2112** [TheDuckCow/godot-road-generator#149]
RoadLanes twist when a RoadSegment is rotated. They should remain straight or, at least, the same as they were before the rotation. Here are some screenshots to demonstrate the problem.

**_In this screenshot, a 2x2 Road is added to an empty scene. "Draw Lanes Editor" is enabled. So, we see orange triangles depicting the RoadLanes and they are straight._**
![ai_lanes_02](https://github.com/TheDuckCow/godot-road-generator/assets/115952055/09dd9c28-f021-4d8d-9c79-8aaca3bc750d)

**_In this screenshot, the 2x2 Road has been rotated 45° and the RoadLanes are now twisted. They should be straight like they were in the first image._**
![ai_lanes_03](https://github.com/TheDuckCow/godot-road-generator/assets/115952055/4d5099db-3c95-4d54-8d1d-bc912994f804)

**Comment by TheDuckCow** [comment]
Closing this issue as the fix was made by
