### ISSUE TITLE
Unexpected RoadLanes created when RoadPoints are moved

### ISSUE THREAD

**Issue by bdog2112** [TheDuckCow/godot-road-generator#154]
Observed an issue where unexpected RoadLanes were created. This led to other unexpected behavior.

How to recreate problem:
- Open Main or Dev branch
- Switch to code editor, append sample code to end of RoadSegment.generate_lane_segments (see below)
- Save and restart
- Create a new scene with a RoadContainer as root
- Add a 2x2 Road from the menu in the 3D view
- Select RP_001 and RP_002 in the Scene dock
- Drag transform widgets to move the RoadPoints in the 3D view
- Upon release, observe message in Output panel saying, "RP_001 has 8 RoadLanes" or something to that effect.

***A 2x2 road should have only 4 RoadLanes.***

[Sample Code]
	var count = 0
	for ch in _par.get_children():
		if ch is RoadLane:
			count += 1
	print("%s %s has %s RoadLanes" % [Time.get_ticks_msec(), _par.name, count])
	return any_generated

**Comment by TheDuckCow** [comment]
This was inadvertently resolved by https://github.com/TheDuckCow/godot-road-generator/pull/164, closing now
