### ISSUE TITLE
Center Curve not removed when Create Edge Curves unchecked

### ISSUE THREAD

**Issue by bdog2112** [TheDuckCow/godot-road-generator#159]
Users can create Edge Curves by selecting a RoadContainer and clicking the "Create Edge Curves" checkbox in the Inspector panel. When they uncheck the checkbox, all Edge Curves should be removed including the "edge_C" curve. However, edge_C does not currently get removed.

A minor update to the RoadSegment.clear_edge_curves routine should fix the issue. Updater should also utilize the edge constants found at the top of the RoadSegment class.

**Comment by TheDuckCow** [comment]
Thanks for flagging - will be good to have a fix for the next public release, but I'd say we don't have to worry about this imminently for the Wheel Steal playtest, unless you have an immediate idea on how to address (I'm guessing it'll be easy for me to investigate later if it comes to that).

**Comment by bdog2112** [comment]
The fix is simple and I've already implemented it in my local copy in the WS project. I'll update the GRG project when time permits.
