### ISSUE TITLE
Not an issue but question

### ISSUE THREAD

**Issue by renzo-massaro** [TheDuckCow/godot-road-generator#179]
Hi :)

Is there any progression with terrain roads? And specifically with the heights and place a road on the different heights??

**Comment by TheDuckCow** [comment]
Hi @renzo-massaro - primary tracker for this feature (if I understand you correctly) is [listed here](https://github.com/TheDuckCow/godot-road-generator/issues/144). If you don't mind, I'll respond to your question there to avoid duplicates, thanks!
