### ISSUE TITLE
Deleting a road point requires a scene reload in order to take effect

### ISSUE THREAD

**Issue by bdog2112** [TheDuckCow/godot-road-generator#39]
When a road point is deleted, errors are printed in the debug window and the removed road point is redrawn in a haphazard way. The scene must be saved and re-loaded in order for the change to fully take effect. Deleting a road point should result in a clean redraw with the road point removed and without the need to reload the scene.

In the example, below, the top road was identical to the bottom road. Then, the right-most road point was deleted from the top road. Finally, the deleted road point appeared to wrap around towards the world origin.
![bug2](https://user-images.githubusercontent.com/115952055/213090965-a183033d-02cb-4645-a7d7-9c77208a4d4d.png)

**Comment by TheDuckCow** [comment]
Closing this as this task has already been resolved thanks to recent work to make deletions much smoother and predictable.
