### ISSUE TITLE
Intermittent clear_lane_segments error when transforming road points

### ISSUE THREAD

**Issue by bdog2112** [TheDuckCow/godot-road-generator#48]
Intermittent error shows up when transforming road points:

> res://addons/road-generator/road_network.gd:168 - Invalid call. Nonexistent function 'clear_lane_segments' in base 'Nil'.

Not sure of the best way to recreate problem. But, try the following:

- Open demo.tscn
- Select neg1_point and make it visible
- Transform, rotate, or move handles

This should result in the error message denoted above. It may be that only the start of a road network is affected.

So, a temporary workaround may be to not select/transform a road's start point.

**Comment by TheDuckCow** [comment]
I tried replicating this just now, and it seems we no longer have the error. We might however get the following warning printouts:

`modules/gdscript/gdscript_functions.cpp:789 - RP should have been present in container edge list`

But, on using the refresh roads button, all gets resolved as the edge list is updated. The only question in my mind here is whether we should in this scenario just auto update the edge list, but I worry about some edge cases which could lead to a lot of extra runtime processing. So I'm going to suggest avoiding it for now. I'm inclined to close this issue in the meantime, given its age.
