### ISSUE TITLE
Lane widget regression

### ISSUE THREAD

**Issue by bdog2112** [TheDuckCow/godot-road-generator#96]
When using the lane widget, sometimes the left handle jumps over to the right handle when released. The problem seems to have materialized after commit [3c1fd74](https://github.com/TheDuckCow/godot-road-generator/commit/cd32fb7d4a354756d26a792ab2c9da0b4c273f85) and on or before commit [41647d9](https://github.com/TheDuckCow/godot-road-generator/commit/41647d9d45edbe3bc9fddf5218ff175756d4793d). Problem doesn't prevent user from adding/removing lanes. But, it is a nuisance.

In the picture, below, we see a normal lane widget on the left and a glitched one on the right:
![Glitch](https://user-images.githubusercontent.com/115952055/236109452-61ef6913-15f2-479e-b2ba-d0ed8a20a4b2.png)

STEPS TO RECREATE PROBLEM:
- Checkout commit [41647d9](https://github.com/TheDuckCow/godot-road-generator/commit/41647d9d45edbe3bc9fddf5218ff175756d4793d) or later
- Create a 2x2 road
- Select the top RoadPoint
- Click/drag the LEFT handle back and forth a few times. Then, release it back at the position where you clicked it
- Now, hover back and forth over the LEFT handle a few times. (But, don't click it.)
- LEFT handle should unexpectedly jump to the RIGHT handle

**Comment by TheDuckCow** [comment]
Confirmed I find the same on the current dev branch. Not ideal, though nice that it does at least reset if you change your selection and re-click. I also find that sometimes the lane markers are sort of inconsistent when they snap into place.

Marking it as a low priority bug for now given the workaround / dealing with it is not that severe (but we will want to address at some point).

**Comment by TheDuckCow** [comment]
Per linked issue, this has already been resolved.
